

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "kip-sql"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false


[dependencies]
log = "^0.4"
sqlparser = "0.34.0"
thiserror = "1"
parking_lot = "0.12.1"
itertools = "0.10"
sqllogictest = "0.11.1"
rust_decimal = "1"
paste = "1.0.11"
tracing = "0.1.37"
pin-project = "1.1.0"
chrono = "0.4.26"
roaring = "0.10.1"
educe = "0.4"
num-traits = "0.2"
num-derive = "0.3"
anyhow = "1.0.71"
tokio = { version = "1.28.2", features = ["full"] }
tokio-process = "0.2.5"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
async-trait = "0.1.68"
snowflake = "1.3.0"

[dev-dependencies]
ctor = "0.2.0"
env_logger = "0.10"
paste = "^1.0"
rstest = "0.17"
